# Generated by Django 5.2.6 on 2025-11-02 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True, verbose_name='كود الطالب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('religion', models.CharField(choices=[('islam', 'إسلام'), ('christianity', 'مسيحية'), ('judaism', 'يهودية'), ('other', 'أخرى')], max_length=20, verbose_name='الديانة')),
                ('nationality', models.CharField(choices=[('egyptian', 'مصري'), ('foreign', 'أجنبي')], max_length=20, verbose_name='التبعية')),
                ('registration_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق'), ('graduated', 'متخرج')], max_length=20, verbose_name='حالة القيد')),
                ('registration_type', models.CharField(choices=[('regular', 'عادي'), ('transfer', 'منقول'), ('repeat', 'مكرر')], max_length=20, verbose_name='نوع القيد')),
                ('section', models.CharField(max_length=100, verbose_name='الشعبة')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('birth_governorate', models.CharField(max_length=100, verbose_name='محافظة الميلاد')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='السن')),
                ('exam_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='السن عند الامتحان')),
                ('school', models.CharField(max_length=200, verbose_name='المدرسة')),
                ('guardian_name', models.CharField(max_length=200, verbose_name='اسم ولي الأمر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلبة',
                'ordering': ['student_code'],
            },
        ),
    ]
