# Generated by Django 5.2.6 on 2025-11-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('رسمي', 'رسمي'), ('خدمات', 'خدمات')], max_length=20, verbose_name='التبعية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_status',
            field=models.CharField(choices=[('ناجح ومنقول', 'ناجح ومنقول'), ('راسب وباق للإعادة', 'راسب وباق للإعادة')], max_length=30, verbose_name='حالة القيد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_type',
            field=models.CharField(choices=[('نظامي', 'نظامي'), ('عمال', 'عمال')], max_length=20, verbose_name='نوع القيد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('مسلمة', 'مسلمة'), ('مسيحية', 'مسيحية')], max_length=20, verbose_name='الديانة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('فني مبيعات', 'فني مبيعات'), ('فني تأمين', 'فني تأمين'), ('تأمين', 'تأمين'), ('عامة', 'عامة')], max_length=100, verbose_name='الشعبة'),
        ),
    ]
