# Generated by Django 5.2.6 on 2025-11-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0002_alter_student_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='صورة الطالب'),
        ),
        migrations.CreateModel(
            name='StudentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='students/attachments/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='student_affairs.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مرفق طالب',
                'verbose_name_plural': 'مرفقات الطلبة',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
