# Generated by Django 5.2.6 on 2025-11-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0003_student_photo_studentattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='المدرسة', max_length=200, verbose_name='اسم المدرسة')),
                ('administration', models.CharField(default='الإدارة التعليمية', max_length=200, verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='العام الأكاديمي'),
        ),
        migrations.AddField(
            model_name='student',
            name='administration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الإدارة'),
        ),
        migrations.AddField(
            model_name='student',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الصف'),
        ),
    ]
