# Generated by Django 5.2.6 on 2025-11-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0004_sitesettings_student_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_round',
            field=models.CharField(blank=True, choices=[('دور أول', 'دور أول'), ('دور ثاني', 'دور ثاني'), ('باقي', 'باقي')], max_length=20, null=True, verbose_name='حالة الطالب (الدور)'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_foreign_language',
            field=models.CharField(blank=True, choices=[('إنجليزي', 'اللغة الإنجليزية'), ('فرنسي', 'اللغة الفرنسية'), ('ألماني', 'اللغة الألمانية'), ('إيطالي', 'اللغة الإيطالية'), ('إسباني', 'اللغة الإسبانية'), ('لغة أخرى', 'لغة أخرى')], max_length=20, null=True, verbose_name='اللغة الأجنبية الأولى'),
        ),
        migrations.AddField(
            model_name='student',
            name='foreign_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ ميلاد الوافد'),
        ),
        migrations.AddField(
            model_name='student',
            name='foreign_birth_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل ميلاد الوافد'),
        ),
        migrations.AddField(
            model_name='student',
            name='foreign_gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='نوع الوافد'),
        ),
        migrations.AddField(
            model_name='student',
            name='inclusion_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تفاصيل الإعاقة (إن وجدت)'),
        ),
        migrations.AddField(
            model_name='student',
            name='inclusion_status',
            field=models.CharField(choices=[('لا يوجد', 'لا يوجد'), ('بصري', 'إعاقة بصرية'), ('سمعي', 'إعاقة سمعية'), ('حركي', 'إعاقة حركية'), ('صعوبات تعلم', 'صعوبات تعلم'), ('أخرى', 'أخرى')], default='لا يوجد', max_length=20, verbose_name='موقف الدمج'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_foreign_student',
            field=models.BooleanField(default=False, verbose_name='طالب وافد'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_returnee',
            field=models.BooleanField(default=False, verbose_name='عائد'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_foreign_language',
            field=models.CharField(blank=True, choices=[('إنجليزي', 'اللغة الإنجليزية'), ('فرنسي', 'اللغة الفرنسية'), ('ألماني', 'اللغة الألمانية'), ('إيطالي', 'اللغة الإيطالية'), ('إسباني', 'اللغة الإسبانية'), ('لغة أخرى', 'لغة أخرى')], max_length=20, null=True, verbose_name='اللغة الأجنبية الثانية'),
        ),
        migrations.AddField(
            model_name='student',
            name='transferred_from',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محول من'),
        ),
        migrations.AddField(
            model_name='student',
            name='transferred_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محول إلى'),
        ),
    ]
