# Generated by Django 5.2.6 on 2025-11-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0005_student_exam_round_student_first_foreign_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_code',
            field=models.CharField(default='', max_length=50, verbose_name='كود الإدارة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='directorate',
            field=models.CharField(default='', max_length=200, verbose_name='المديرية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='school_serial',
            field=models.CharField(default='', max_length=50, verbose_name='مسلسل المدرسة'),
        ),
        migrations.AddField(
            model_name='student',
            name='admin_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الإدارة'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مسلسل المدرسة'),
        ),
    ]
