# Generated by Django 5.2.6 on 2025-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0006_sitesettings_admin_code_sitesettings_directorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='school_manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مدير المدرسة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='student_affairs_deputy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وكيل شؤون الطلبة'),
        ),
    ]
