# Generated by Django 5.2.6 on 2025-11-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0007_sitesettings_school_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_withdrawn',
            field=models.BooleanField(default=False, verbose_name='سحب'),
        ),
    ]
