# Generated by Django 5.2.6 on 2025-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0008_student_is_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_round',
            field=models.CharField(blank=True, choices=[('دور أول', 'دور أول'), ('دور ثاني', 'دور ثاني'), ('باقي', 'باقي'), ('سحب', 'سحب')], max_length=20, null=True, verbose_name='حالة الطالب (الدور)'),
        ),
    ]
