# Generated by Django 5.2.6 on 2025-11-03 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0009_alter_student_exam_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('g1', 'الصف الأول'), ('g2', 'الصف الثاني'), ('g3', 'الصف الثالث')], max_length=2, verbose_name='الصف')),
                ('gender', models.CharField(choices=[('male', 'بنين'), ('female', 'بنات')], max_length=6, verbose_name='النوع')),
                ('class_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='رقم الفصل')),
                ('seats_count', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد المقاعد')),
                ('floor', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الطابق')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الفصل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['grade', 'class_number'],
                'unique_together': {('grade', 'gender', 'class_number')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_affairs.classroom', verbose_name='الفصل'),
        ),
    ]
